API.md
ocean_provider/contracts/factory.py
ocean_provider/routes.py
ocean_provider/user_nonce.py
ocean_provider/util.py
ocean_provider/utils/accounts.py
ocean_provider/web3_internal/contract_base.py
ocean_provider/web3_internal/contract_handler.py
ocean_provider/web3_internal/web3helper.py
tests/conftest.py
tests/test_compute.py
tests/test_download.py
tests/test_helpers.py

Introduce nonce in signatures for added security.

Use nonce in user signature.

---

ocean_provider/util.py
setup.py

update ocean.py version, retry fetching tx receipt on connectionclosed error.

update ocean.py and handle connectionclosed error

---

ocean_provider/routes.py
ocean_provider/util.py
tests/ddo/ddo_sample_invalid_url.json
tests/ddo/ddo_sample_ipfs_url.json
tests/test_compute.py
tests/test_helpers.py

Closes #42. Closes #16. Closes #45.

Adds checkURL endpoint.

---

ocean_provider/routes.py
ocean_provider/run.py
tests/test_compute.py

Added a new dictionary ('serviceEndpoints') in run.py file, in function version with all types of existed endpoints from routes.py. Tested the functionality by implementing a new unit test in test_compute.py.
closes #36

Expose service endpoints

---

README.md
ocean_provider/routes.py
setup.py

Another possible improvement to the deployment flow: implement a git pre-commit hook calling flake8 to avoid formatting issues on commit.

[Proposal] Adds flake8 and git hook.

---

.bumpversion.cfg
ocean_provider/routes.py
ocean_provider/util.py
setup.py
tests/test_compute.py
tests/test_download.py

Add endpoint for assetInfo

---

ocean_provider/access_token.py
ocean_provider/requests.py
ocean_provider/routes.py
ocean_provider/utils/encryption.py
tests/test_access_token.py

Related to #55 .
- adds token usage in download endpoint

Adds access token usage in download.

---

.env.example
README.md
setup.py

This is something I discovered during initial setup. I believe using dotenv would be easier, and I decided to make it so.
Please ignore/close PR if not a good idea :)

[Proposal] Adds support for dotenv in provider.

---

ocean_provider/user_nonce.py

Fixes #62
- make a new db connection on each call

create new sqlite db connection on each call

---

.bumpversion.cfg
ocean_provider/util.py
setup.py

Do not require Content-Length

---

.bumpversion.cfg
ocean_provider/util.py
ocean_provider/utils/accounts.py
setup.py

add timeouts for requests

---

Dockerfile
ocean_provider/config.py
ocean_provider/util.py
ocean_provider/util_url.py
setup.py
tests/test_utils.py

Secures urls
Any URL must be verified
- if it's a valid URL
- if the domain resolves to an ip address
- if the ipaddress is a public one (not loopback, not reserved, etc)

secure urls

---

ocean_provider/routes.py

Fixes #76.
- add correct docs formatting for swagger

Corrects docs for Swagger representation.

---

ocean_provider/exceptions.py
ocean_provider/routes.py
ocean_provider/util.py
ocean_provider/validation/requests.py

- adapts Compute request to new Flask sieve validation

Adds compute request validation improvements.

---

.github/workflows/tox.yml
ocean_provider/run.py
tests/test_compute.py

Fixes #117.
- retrieves the provider wallet address.

Getter for provider address

---

setup.py

Bump ocean-lib

---

db/.gitignore
ocean_provider/config.py
ocean_provider/myapp.py

[Bugfix] Adds sqlite file in different folder to mount + fallback.

---

.github/workflows/black.yml
.pre-commit-config.yaml
README.md
ocean_provider/config.py
ocean_provider/constants.py
ocean_provider/exceptions.py
ocean_provider/log.py
ocean_provider/models.py
ocean_provider/myapp.py
ocean_provider/routes.py
ocean_provider/routes/__init__.py
ocean_provider/routes/compute.py
ocean_provider/routes/consume.py
ocean_provider/run.py
ocean_provider/user_nonce.py
ocean_provider/util.py
ocean_provider/util_url.py
ocean_provider/utils/accounts.py
ocean_provider/utils/basics.py
ocean_provider/utils/encryption.py
ocean_provider/utils/web3.py
ocean_provider/validation/algo.py
ocean_provider/validation/requests.py
setup.cfg
setup.py
tests/conftest.py
tests/test_compute.py
tests/test_download.py
tests/test_helpers.py
tests/test_utils.py

Add Black autoformatting and pre-commit hooks. Separate compute and consume routes.

---

ocean_provider/config.py
ocean_provider/routes/compute.py
ocean_provider/serializers.py
ocean_provider/util.py
ocean_provider/util_url.py
ocean_provider/validation/algo.py
tests/test_compute.py
tests/test_helpers.py

Remote asset

---

ocean_provider/validation/algo.py

Important fix to avoid circularity.

---

ocean_provider/config.py
tests/resources/test-config.txt
tests/test_config.py

Fix typo in provider settings.

---

ocean_provider/myapp.py
ocean_provider/validation/algo.py
tests/test_algo_validation.py

Change a confusing error message

---

ocean_provider/database.py
ocean_provider/models.py
ocean_provider/myapp.py
ocean_provider/user_nonce.py
setup.py

At Samer's request. Possibly a step towards #114.

Replace flask-sql alchemy with sql-alchemy.

---

ocean_provider/routes/compute.py

Nonce should be incremented only if signature is provider

fix compute status nonce increment

---

.bumpversion.cfg
setup.py

bump version

---

.bumpversion.cfg
ocean_provider/serializers.py
ocean_provider/validation/algo.py
setup.py

Fixes missing service in StageAlgoValidator.

---

ocean_provider/exceptions.py

Test branch to check if Code Climate picks it up. Fixes a pre-commit issue, so it can be merged.

Fixes a pre-commit issue.

---

ocean_provider/exceptions.py
ocean_provider/util_url.py
setup.py

Catch ReadTimeout exception.

---

ocean_provider/routes/compute.py
ocean_provider/util.py
ocean_provider/utils/accounts.py
setup.py
tests/conftest.py
tests/test_compute.py
tests/test_download.py
tests/test_helpers.py

Towards https://github.com/oceanprotocol/ocean.py/issues/304

Replace usages of Web3Helper with module functions from transactions and utils

---

ocean_provider/routes/consume.py
ocean_provider/utils/util.py
ocean_provider/validation/algo.py
setup.py
tests/test_download.py
tests/test_helpers.py

Add checks for accessing a request

---

ocean_provider/routes/consume.py

Fixes #143.
- Minor docstring improvement

Improvement: Change docstring for generating markdown

---

ocean_provider/utils/basics.py
setup.py
tox.ini

Towards https://github.com/oceanprotocol/multi-repo-issue/issues/83
- Upgrade to ocean_lib 0.5.22
- Eliminate use of VIRTUAL_ENV
- Fix deps tag in tox.ini

Feature/upgrade to ocean lib v0.6.3

---

tests/ddo/ddo_sa_sample_multiple_files.json
tests/test_download.py
tests/test_helpers.py

Fixes #54 .
- created an unit test to see if there is an issue or not;
- added a new ddo sample with multiple files.

Multiple files downloaded

---

.bumpversion.cfg
ocean_provider/routes/consume.py
ocean_provider/utils/basics.py
setup.py
tests/test_helpers.py

get minter from contract

---

ocean_provider/utils/test/test_util.py
ocean_provider/utils/util.py

Fixes a failure of provider with hangup.

---

ocean_provider/utils/url.py
tests/test_fileinfo.py

Closes #158 #161.
-  add a HEAD request in fileinfo, before OPTIONS
- fallback on Content-Range if Content-Length is missing
- strip the charset part of contentType

Adds head method on requests.

---

ocean_provider/routes/compute.py
ocean_provider/utils/accounts.py
ocean_provider/utils/basics.py
ocean_provider/utils/util.py
ocean_provider/validation/RBAC.py
setup.py
tests/helpers/compute_helpers.py
tests/test_compute.py
tests/test_download.py
tests/test_helpers.py
tests/test_routes.py

Closes #166. Was previously approved but solved conflicts.

Issue 166 remove contract handler 3

---

conftest.py
ocean_provider/routes/compute.py
ocean_provider/routes/consume.py
ocean_provider/utils/accounts.py
ocean_provider/utils/basics.py
ocean_provider/utils/util.py
ocean_provider/validation/algo.py
ocean_provider/validation/test/test_algo_validation.py
setup.py
tests/helpers/compute_helpers.py
tests/test_RBAC.py
tests/test_compute.py
tests/test_download.py
tests/test_helpers.py

Upgrades ocean.py to 0.5.26.

---

ocean_provider/routes/consume.py
ocean_provider/serializers.py
ocean_provider/utils/url.py
ocean_provider/validation/algo.py
tests/test_compute.py
tests/test_download.py

Add userdata to compute and access endpoints

---

ocean_provider/routes/consume.py

Need to add userdata to initialize as well. Not sure if this is the required change but I couldn't find another URL on initialize, so I hope this is fine. Let me know if it needs anything else. :)

Add userdata to initialize.

---

ocean_provider/validation/algo.py
ocean_provider/validation/test/test_algo_validation.py
tests/helpers/compute_helpers.py
tests/helpers/service_descriptors.py

No issue to close yet. Will update that if necessary.
Btw, I used `trustedAlgorithmPublishers` as a key instead of `publisherTrustedAlgorithmPublishers` but I can change that. It seemed simpler.

Adds trusted publishers.

---

ocean_provider/constants.py
ocean_provider/database.py
ocean_provider/models.py
ocean_provider/myapp.py
ocean_provider/routes/consume.py
ocean_provider/user_nonce.py
ocean_provider/utils/accounts.py
ocean_provider/utils/basics.py
ocean_provider/utils/encryption.py

Improvement: Add docstrings

---

Dockerfile

Fixes #189
Test:
Here's the console log building the docker image. As you can see, the `invalid_command bdist_wheel` errors are no longer present.
```console
(venv) david@david-Inspiron-5502:~/projects/provider$ docker build -t oceanprotocol/my-provider-py .
... snip ...
Step 8/28 : RUN python3.8 -m pip install wheel
---> Running in 4328fbcf6214
Collecting wheel
Downloading https://files.pythonhosted.org/packages/65/63/39d04c74222770ed1589c0eaba06c05891801219272420b40311cd60c880/wheel-0.36.2-py2.py3-none-any.whl
Installing collected packages: wheel
Successfully installed wheel-0.36.2
Removing intermediate container 4328fbcf6214
---> 650d81b27757
Step 9/28 : RUN python3.8 -m pip install .
---> Running in 5dfa8fbd47f4
Processing /ocean-provider
Requirement already satisfied (use --upgrade …
```

Add wheel to Dockerfile. Fix "invalid command bdist_wheel" errors.

---

ocean_provider/validation/algo.py

Fixes #187 .
- add the error flag `DISCARD` to `processReceipt`.

Remove ABI Mismatch warning

---

ocean_provider/routes/compute.py
ocean_provider/routes/consume.py
ocean_provider/run.py
tox.ini

Towards #173 
- Add INFO log statements to the beginning of each route
* Attempted DEBUG logs instead of INFO, but they don't appear, even when LOG_LEVEL=DEBUG.

Issue173 add more log statements

---

setup.py

Closes https://github.com/oceanprotocol/ocean.py/issues/423. Closes #193.

Upgrade lib version, no other changes.

---

.bumpversion.cfg
setup.py

Ocean.py fixes from David, needs releasing.

Version 0.4.14

---

ocean_provider/routes/compute.py
ocean_provider/utils/accounts.py
ocean_provider/utils/util.py
ocean_provider/validation/provider_requests.py
tests/helpers/compute_helpers.py
tests/test_compute.py

add computeResult endpoint

---

.bumpversion.cfg
setup.py

Bump version: 0.4.14 → 0.4.15

---

.bumpversion.cfg
ocean_provider/routes/compute.py
ocean_provider/routes/consume.py
ocean_provider/run.py
ocean_provider/utils/util.py
setup.py

expose more compute limits

---

ocean_provider/utils/util.py
ocean_provider/validation/algo.py
setup.py
tests/test_download.py
tests/test_helpers.py

Closes #211. Still a draft because we are waiting for ocean.py 0.6.1 with the new contracts.

Upgrade ocean to 0.6.1

---

API.md
README.md
deployment/README.md
deployment/provider-standard-networks-deployment-example.yaml
ocean_provider/constants.py
ocean_provider/utils/basics.py
ocean_provider/utils/util.py
tests/ddo/ddo_sa_sample.json
tests/ddo/ddo_sa_sample_multiple_files.json
tests/ddo/ddo_sa_sample_with_credentials.json
tests/ddo/ddo_sample_algorithm.json
tests/ddo/ddo_sample_invalid_url.json
tests/ddo/ddo_sample_ipfs_url.json
tests/ddo/ddo_with_compute_service.json
tests/test_helpers.py

Fixes #197  .
- Removed `v1` from the base endpoints

Removed v1 from the base endpoint

---

ocean_provider/validation/RBAC.py
tests/test_RBAC.py

Fixes #225  .
- modify the unit tests for RBAC;
- added `did` key to the requests' structures;
- changed the `type` key.

Updated RBAC requests.

---

README.md

Fixes #234
- Update README.md file

Issue-#234: Fix property name in README.md

---

tests/test_RBAC.py

Fixes #255  .
- added assertions for `providerAddress`

Added assetions for providerAddress.

---

ocean_provider/models.py
ocean_provider/test/test_user_nonce.py
ocean_provider/user_nonce.py

Fixes #273 .
- Cherry pick 7207e078c5b96457711581545424befbd759da47 (#268)

Issue273 fix increment nonce

---

ocean_provider/test/test_user_nonce.py
ocean_provider/user_nonce.py
pytest.ini
setup.py

Adds Redis option for nonce.

---

ocean_provider/routes/consume.py
ocean_provider/validation/provider_requests.py
tests/test_download.py

Asset urls v3

---

ocean_provider/routes/consume.py
ocean_provider/test/test_user_nonce.py
ocean_provider/utils/test/test_util.py
ocean_provider/utils/util.py
ocean_provider/validation/provider_requests.py
tests/helpers/ddo_dict_builders.py
tests/test_download.py
tests/test_fileinfo.py
tests/test_helpers.py

Ddo storage structure

---

tests/test_RBAC.py

Lighten RBAC tests.

---

README.md
ocean_provider/utils/url.py

Add retry mechanism (v4)

---

README.md
ocean_provider/utils/url.py

Retry mechanism v3

---

ocean_provider/serializers.py

Send algouserdata to c2d using the workflow
- 
- 
-

send algouserdata to workflow

---

.bumpversion.cfg
setup.py

Bump version: 0.4.18 → 0.4.19

---

API.md
ocean_provider/routes/consume.py
ocean_provider/utils/credentials.py
ocean_provider/utils/url.py
tests/test_helpers.py

A couple of fixes for errors encountered during ocean.js development

fixes on initialize & download

---

.bumpversion.cfg
ocean_provider/validation/algo.py
setup.py

Add correct userdata in input.

---

ocean_provider/routes/compute.py

- simplify compute status, we don't need signatures any more for this endpoint
- 
-

simply compute status

---

ocean_provider/routes/consume.py
ocean_provider/utils/datatoken.py
ocean_provider/utils/util.py
ocean_provider/validation/algo.py
ocean_provider/validation/test/test_algo_validation.py
tests/test_download.py
tests/test_helpers.py

Issue 331 dt check

---

ocean_provider/routes/compute.py
ocean_provider/utils/provider_fees.py

For now, have a mock endpoint that is going to be used by ocean.js/py.
Will evolve this once c2d is ready

mock C2d environments endpoint

---

ocean_provider/routes/compute.py
ocean_provider/utils/provider_fees.py

Signed-off-by: Pablo Maldonado <pablo@oceanprotocol.com>
Fixes #339 .
- Fix typo in computeEnvironments

Fix typo in computeEnvironments endpoint

---

ocean_provider/utils/test/test_util.py
ocean_provider/utils/util.py

Issue 342 slashes

---

.github/workflows/pytest.yml

add docker build check

---

ocean_provider/utils/asset.py
ocean_provider/validation/test/test_algo_validation.py
tests/helpers/compute_helpers.py
tests/test_RBAC.py
tests/test_compute.py
tests/test_download.py
tests/test_fileinfo.py
tests/test_helpers.py

Only keep 1st service retrieval in tests.

---

ocean_provider/routes/compute.py
ocean_provider/routes/consume.py
ocean_provider/utils/datatoken.py
ocean_provider/utils/provider_fees.py
ocean_provider/utils/test/test_provider_fees.py
ocean_provider/utils/util.py
ocean_provider/validation/algo.py
ocean_provider/validation/test/test_algo_validation.py
setup.py
tests/test_compute.py

Provider fee amount

---

ocean_provider/routes/compute.py
ocean_provider/test/test_user_nonce.py
ocean_provider/utils/datatoken.py
ocean_provider/utils/provider_fees.py
ocean_provider/utils/test/test_accounts.py
ocean_provider/utils/util.py
ocean_provider/validation/provider_requests.py
tests/helpers/compute_helpers.py
tests/test_RBAC.py
tests/test_compute.py
tests/test_download.py
tests/test_encryption.py
tests/test_routes.py

Replace instances of now with utcnow.

---

ocean_provider/routes/consume.py
ocean_provider/utils/basics.py
ocean_provider/validation/provider_requests.py

Fix for validuntil.

---

setup.py

Contracts update to v1.0.0-alpha.20

---

README.md

Document authorized decrypters

---

ocean_provider/routes/decrypt.py
ocean_provider/run.py
ocean_provider/utils/basics.py
ocean_provider/utils/data_nft.py
ocean_provider/utils/data_nft_factory.py
ocean_provider/validation/provider_requests.py
tests/test_encryption.py
tests/test_helpers.py

Decrypt endpoint fails

---

README.md

fix env on README

---

ocean_provider/utils/accounts.py
ocean_provider/utils/test/test_accounts.py
ocean_provider/validation/provider_requests.py
tests/test_download.py

Fixes #385  .
- added logs for the decrypt process;
- fixed download test.

Added logs for decrypt endpoint. Fixed download test.

---

ocean_provider/routes/compute.py
ocean_provider/routes/consume.py
ocean_provider/utils/provider_fees.py
tests/test_compute.py

Allow download only provider, without compute url.

---

.github/workflows/pytest.yml
ocean_provider/routes/compute.py
setup.py
tests/test_helpers.py

Bump contracts to 1.0.0a28

---

.bumpversion.cfg
setup.py

Bump version: 1.0.2 → 1.0.3

---

.github/workflows/pytest.yml
ocean_provider/utils/currency.py
ocean_provider/utils/provider_fees.py
ocean_provider/utils/test/test_currency.py

Fixes #420
- Fix the bug where to_wei didn't handle decimals correctly
- Update test_currency.py
-

Fix bug where to_wei didn't handle decimals correctly

---

ocean_provider/routes/compute.py
ocean_provider/routes/consume.py
ocean_provider/run.py
ocean_provider/utils/asset.py
ocean_provider/utils/basics.py
ocean_provider/utils/compute.py
ocean_provider/utils/compute_environments.py
ocean_provider/utils/datatoken.py
ocean_provider/utils/provider_fees.py
ocean_provider/utils/test/test_compute.py
ocean_provider/utils/test/test_util.py
ocean_provider/utils/util.py
ocean_provider/validation/algo.py
tests/test_helpers.py

Reorganise utils

---

.github/workflows/pytest.yml
ocean_provider/routes/decrypt.py
ocean_provider/utils/data_nft_factory.py

Check deployer factory in decrypt.

---

ocean_provider/routes/compute.py
ocean_provider/routes/consume.py
ocean_provider/routes/decrypt.py
ocean_provider/routes/encrypt.py
ocean_provider/utils/accounts.py
ocean_provider/utils/basics.py
ocean_provider/utils/data_nft.py
ocean_provider/utils/datatoken.py
ocean_provider/utils/encryption.py
ocean_provider/utils/error_responses.py

Fix and add some docstrings.

---

ocean_provider/routes/compute.py
ocean_provider/routes/consume.py
ocean_provider/routes/decrypt.py
ocean_provider/routes/encrypt.py
ocean_provider/utils/basics.py
ocean_provider/utils/provider_fees.py
setup.py

Upgrade flask.

---

.bumpversion.cfg
.github/workflows/pytest.yml
setup.py

Feature/release 1.0.7

---

.bumpversion.cfg
setup.py

bump contracts to alpha 33

---

.bumpversion.cfg
setup.py

bump to contracts 34
Fixes # .
- 
- 
-

bump to contracts 34

---

.bumpversion.cfg
ocean_provider/utils/datatoken.py
setup.py

Fixes issue where wrong tx id was returned if order reused.

---

README.md

Fixes #459 
- Explaining what provider does in the readme

Explaining what provider does in the readme

---

ocean_provider/routes/consume.py
ocean_provider/validation/provider_requests.py
tests/test_helpers.py
tests/test_initialize.py

Adds initialize access check for reuse.

---

API.md

Fixes #468
- Remove link and a statement
- Auto refactored by vscode

Fix API.md file

---

.bumpversion.cfg
setup.py

Feature/contracts 1.0.0

---

.bumpversion.cfg
ocean_provider/utils/provider_fees.py
setup.py

more checksum addrs

---

ocean_provider/utils/test/test_util.py
ocean_provider/utils/util.py

check for unsafe methods

---

.bumpversion.cfg
setup.py

Bump version: 1.0.17 → 1.0.18

---

.github/workflows/pytest.yml
ocean_provider/utils/accounts.py

Fix nonce comparison.

---

ocean_provider/utils/test/test_url.py
ocean_provider/utils/test/test_util.py
ocean_provider/utils/url.py

Adds url redirect checks.

---

.bumpversion.cfg
ocean_provider/utils/datatoken.py
setup.py

use checksum addresses

---

ocean_provider/serializers.py

fix algocustomdata

---

ocean_provider/utils/accounts.py
ocean_provider/validation/algo.py
ocean_provider/validation/test/test_algo_validation.py
tests/test_compute.py

Work on https://github.com/oceanprotocol/multi-repo-issue/issues/154

Adds requirement for docker image checksum.

---

ocean_provider/routes/compute.py
ocean_provider/routes/consume.py
ocean_provider/utils/test/test_util.py
ocean_provider/utils/url.py
ocean_provider/utils/util.py
ocean_provider/validation/algo.py
tests/test_initialize.py

Fix fileinfo validation and support headers

---

.bumpversion.cfg
setup.py

Bump version: 1.0.21 → 1.1.0

---

README.md
ocean_provider/config.py
ocean_provider/utils/basics.py
ocean_provider/utils/test/test_basics.py

Fixes #508  .
- inject PoA middleware for HTTP.

PoA fix also for HTTP provider.

---

ocean_provider/models.py
ocean_provider/myapp.py
ocean_provider/routes/__init__.py
ocean_provider/routes/auth.py
ocean_provider/user_nonce.py
ocean_provider/utils/accounts.py
ocean_provider/validation/provider_requests.py
setup.py
tests/helpers/compute_helpers.py
tests/test_auth.py
tests/test_compute.py
tests/test_download.py

Auth tokens

---

conftest.py
pytest.ini
tests/helpers/compute_helpers.py
tests/test_compute.py
tests/test_initialize.py

Adds paid environment compute test.

---

.bumpversion.cfg
setup.py

Sha3fix + bump version to 1.3.2

---

API.md
tests/test_auth.py

Document auth routes.

---

ocean_provider/routes/consume.py

Fix logging error with file types

---

ocean_provider/routes/consume.py
tests/test_compute.py

Fixes #532 .
- Bind request body userdata to url object

consume download, pass userdata into file url object

---

.bumpversion.cfg
setup.py

Bump version: 1.3.2 → 1.3.3

---

.bumpversion.cfg
ocean_provider/file_types/types/smartcontract.py
setup.py
tests/test_smartcontract.py

Closes #550 
- add "pure" to mutability state for on-chain data (contract calls)
- 
-

add pure mutability

---

.bumpversion.cfg
ocean_provider/file_types/file_types_factory.py
ocean_provider/routes/consume.py
ocean_provider/validation/provider_requests.py
setup.py
tests/test_fileinfo.py

add userdata to initialize & fileinfo endpoint

---

.bumpversion.cfg
ocean_provider/utils/asset.py
setup.py
tests/test_helpers.py
tests/test_initialize.py

Fixes #566 
- is_consumable should allow assets with nft_state = 5
- add test for that
-

allow consumption if state=5

---

API.md

Fixes #547 .
- updated `API.md` with signatures explanations
- enhanced some jsons

Update API.md with signatures explanations

---

.bumpversion.cfg
ocean_provider/routes/decrypt.py
ocean_provider/utils/data_nft.py
setup.py

Closes #582 
- handle MetaDataState.UNLISTED
- 
-

allow unlisted state

---

API.md

Towards #547 .
- added details for signature params

Document signatures in API.md

---

.github/workflows/black.yml
.pre-commit-config.yaml
ocean_provider/file_types/types/smartcontract.py
setup.py

Closes #595 but I am not sure whether this is the intended checksum. I checksummed the ABI of the contract. Is that what you expect @alexcos20 @bogdanfazakas?

Ads smartcontract checksum.

---

ocean_provider/requests_session.py
ocean_provider/utils/compute_environments.py
ocean_provider/utils/test/test_util.py
tests/test_initialize.py

Fixes #608  .
- added Retry class
- kept `request_session` & remove while loop for retrying
- skipped `test_httpbin` when it has downtime.

Added Retry class.

---

ocean_provider/file_types/definitions.py

Use defined method instead of head and options.

---

ocean_provider/run.py
ocean_provider/utils/basics.py
ocean_provider/version.py

Send UserAgent header with RPC calls.

---

tests/helpers/compute_helpers.py
tests/test_compute.py
tests/test_initialize.py

Towards #606 .
- skip tests temporary
- 
-

Skip c2d tests.

---

conftest.py
ocean_provider/utils/compute_environments.py
tests/test_compute.py

Skip if setup fails for environments.

---

ocean_provider/utils/address.py
ocean_provider/utils/asset.py
ocean_provider/utils/data_nft.py
ocean_provider/utils/data_nft_factory.py
ocean_provider/utils/datatoken.py
setup.py
tests/test_helpers.py

Remove jsonsempai.

---

.bumpversion.cfg
setup.py

Bump next version

---

.bumpversion.cfg
setup.py

Bump version: 2.0.1 → 2.0.2

---

.github/workflows/pytest.yml
.gitignore
ocean_provider/utils/test/test_provider_fees.py
ocean_provider/validation/test/test_algo_validation.py
setup.py
tests/test_compute.py
tests/test_fileinfo.py
tests/test_initialize.py

Upgrade contracts version to support Sepolia.

Upgrade contracts version to support Sepolia.

---

.bumpversion.cfg
setup.py

Bump version 2.0.2 -> 2.0.3.

---

ocean_provider/constants.py
ocean_provider/file_types/definitions.py
ocean_provider/routes/README.md
ocean_provider/routes/compute.py
ocean_provider/routes/consume.py
ocean_provider/routes/decrypt.py
tests/test_download.py
tests/test_encryption.py
tests/test_fileinfo.py

Fixes #656  .
- rejected HEAD & OPTIONS requests where nonce is updated in the DB
- add filename to fileinfo endpoint
- tests

Rejected HEAD & OPTIONS requests where nonce is updated in the DB. Add filename to fileinfo endpoint.

---

.bumpversion.cfg
ocean_provider/routes/consume.py
ocean_provider/user_nonce.py
setup.py
tests/helpers/nonce.py
tests/test_routes.py

Added Decimal type for nonce purposes.
Bump version to v2.1.3.

Added Decimal type for nonce purposes

---

setup.py

Fixes #665  .
- Bump contracts version to v1.1.15

Bump contracts version.
