ocean_provider/user_nonce.py

Fix for the following error:
```
2020-09-09 03:54:02 aed285c539cc root[10] ERROR Error reading nonce value for account 0xa0041f95646640DBB8f3f43a96b00C1B27E7596e: no such table: user_nonce
```
It is trying to read nonce before the table is created.

Fix error: missing user_nonce table

---

setup.py

Missing `utils` submodule when running `python setup.py sdist`

Include missing submodule in setup script

---

.github/workflows/tox.yml

Some finding while setting this up over on `market`. Relying on the `v3` branch in barge, and specific versions of Aquarius & contracts is not future-proof. Additionally, the set env vars were never active cause they should be set on the `Run Barge` step. Regardless, I removed them all so testing always happens against latest release versions of everything instead of old branches/versions
Test run now might fail, cause there's this issue I discovered where latest `contracts` builds are not on DockerHub, which probably was the reason to set specific versions https://github.com/oceanprotocol/contracts/issues/265. As soon as hat's available, restarting test runs should make them green

run CI tests against default barge versions

---

ocean_provider/myapp.py

Fixes #101.
- disable SQLALCHEMY_TRACK_MODIFICATIONS for cleaner logs in Barge
- add exception handling on table already exists (fail gracefully)
- no unit test since it can only be reproduced by running in barge. I tried running the app locally in 2 different tabs and both worked fine, even before the fix.

Disable modification tracking and catch table already exists error.

---

bumpversion.sh

Fixes #104.
- Remove references to master branch in code (only found in the bumpversion script).

Remove references to master branch in bumpversion.sh.

---

ocean_provider/validation/RBAC.py
tests/test_RBAC.py

Fixes #186  .
- replace `provider_address` from credentials with the request's consumer address;
- refactor RBAC unit tests;
- remove unused imports.

Refactored the credentials part from RBAC server logic

---

ocean_provider/utils/accounts.py
setup.py

- Remove `ec_recover`, use `recover_message` instead.
Using `recover_message`, the message is still hashed before recovering the signer address.

Remove ec_recover, use recover_message instead

---

ocean_provider/validation/provider_requests.py
tests/helpers/compute_helpers.py
tests/test_compute.py

Closes #204.
@alexcos20 I fixed the crash by bailing if the signature is not sent, but I see that #203 proposes an unsigned version of this endpoint. Can you advise? Should I work on a version where the signature is not required?

Fix crash when signature is not sent on ComputeResult.

---

ocean_provider/routes/compute.py
tests/test_compute.py

Closes #203 
GET /compute should:
1. filter old format fields ("resultsUrl",   "algorithmLogUrl",  "resultsDid").  This fields are still available with a signature (backwards compat)
2. should not filter results fields, because that is public

fix unsigned get compute result  (pass results)

---

ocean_provider/validation/provider_requests.py
setup.py
tests/helpers/compute_helpers.py

Signed-off-by: Pablo Maldonado <pablo@oceanprotocol.com>
Fixes #236 .
- Update flask-sieve version to `v1.3.1` to fix the documented problem : `0` and `false` values were making the rule required fail . See: https://github.com/codingedward/flask-sieve/releases/tag/v1.3.1
- Replaced non-existing module `tests.helpers.service_definitions` with `tests.helpers.ddo_dict_builders`
- Prior to this update, some tests were already failing. The flask-sieve version upgrade doesn't seem to introduce new problems:
Tests run with `flask-sieve==1.2.2` **without flags and nonce validation rules**: 28 Failed, 37 Passed, 69 Warnings
Tests run with `flask-sieve==1.3.1` [**with flags and nonce validation rules**](https://github.com/oceanprotocol/provider/blob/290f6f17d2f20ec04e052 …

Fix decrypt endpoint request validation

---

ocean_provider/utils/address.py
ocean_provider/utils/data_nft_factory.py
ocean_provider/utils/test/test_address.py
tests/ddo/ddo_event_sample_v4.py
tests/ddo/ddo_sample1_v4.py
tests/ddo/ddo_sample_algorithm_v4.py
tests/test_encryption.py
tests/test_helpers.py

Closes #246 
- Remove all the places `1337` is used as the chain_id.
- Replace hardcoded `chain_id`s with `web3.eth.chain_id` wherever possible
- Add `get_address_json` and `get_contract_address` utils
- Add `test_get_address_json` and `test_get_contract_address` unit tests
- Remove `CHAIN_ID_TO_NETWORK_NAME` map. Use new address utils instead.
The newly added unit tests are passing, but many of the other unit tests are still in a broken state.
```
ocean_provider/utils/test/test_address.py ..                             [ 16%]
```

Issue246 ganache chain id 8996

---

tests/test_helpers.py

Changes:
* Eliminate MismatchedABI warnings clogging pytest output by discarding errors that occur while processing transaction receipts.
* Also, minor formatting changes by `black` and `isort`
Proof of fix: 
Observe that the tox logs in the checks no longer contain MismatchedABI warnings.

Eliminate MismatchedABI warnings clogging pytest output

---

ocean_provider/routes/consume.py
ocean_provider/utils/datatoken.py

- Fixes the remaining TODOs in the `download` endpoint.
- Populate the `contentType` attribute in the `Response`
- Remove TODO related to service validation. `validate_order` already validates that the `serviceIndex` provided by the caller matches the `serviceIndex` in the `OrderStarted` event. 
- Replaced an `assert` statement with an `if + exception` in production code.
- Minor formatting changes from pre-commit checks (black, isort, and flake)

Fix todos in download endpoint

---

ocean_provider/routes/compute.py
ocean_provider/routes/consume.py
ocean_provider/utils/error_responses.py
ocean_provider/utils/test/test_error_responses.py
ocean_provider/utils/test/test_util.py
ocean_provider/utils/util.py

Fixes #287
- Fix bug where `service_unavailable` would leak Infura project ID to the caller of provider endpoints.
- Add `strip_infura_project_id` utility
- Add `test_service_unavailable_strip_infura_project_id` unit test
- Move `service_unavailable` to `utils/error_responses.py`
- Move related unit tests to `utils/test/test_error_responses.py`
- Update log statement inside `service_unavailable` to print error message
- Various black formatting fixes

Issue287 prevent leaking infura project id

---

ocean_provider/utils/error_responses.py
ocean_provider/utils/test/test_error_responses.py
ocean_provider/utils/test/test_url.py
ocean_provider/utils/url.py

Fixes #292 .
- Cherry-pick https://github.com/oceanprotocol/provider/commit/3c67cbb06b10242a35e1f1b30d2da4ada9baa7fa. This makes it so the `service_unavailable` function strips out all URLs, not just Infura project IDs.

Strip all URLs, not just infura project ids (v3)

---

ocean_provider/utils/datatoken.py
setup.py
tests/test_helpers.py

Towards #284
- Upgrade web3.py to 5.25.0
- Add `gasPrice` to transactions, continue using legacy transaction type
- Add `get_gas_price` helper function
- Reformat via black, isort, flake

Issue284 upgrade web3 py (v3)

---

ocean_provider/utils/provider_fees.py

- Fix computeEnvironment endpoint error handling. If exception occurs when calling c2d backend, let handle_error return 503, service unavailable.

Fix computeEnvironment endpoint error handling

---

ocean_provider/config.py
ocean_provider/routes/compute.py
ocean_provider/utils/url.py
ocean_provider/utils/util.py

Fixes #386 #391 #396
1. config.allow_non_public_ip() to return a Boolean type by setting ALLOW_NON_PUBLIC_IP environment variable as "0" or "1"
2. Validate DNS base on hostname instead of netloc (hostname:port) of an URL
3. Fix URL validation failure if a URL with IP and no Port been passed
4. GET /computeResult to skip the DNS validation, as an internal operator-api URL might be configured

Fix various issues of allow non public ip configuration

---

ocean_provider/config.py
ocean_provider/test/test_config.py
ocean_provider/utils/url.py

Signed-off-by: Pablo Maldonado <pablo@oceanprotocol.com>
Fixes #400  .
-  Fix errors in `allow_non_public_ip` from `config.py`

Fix allow allow_non_public_ip & add tests

---

ocean_provider/routes/compute.py
ocean_provider/routes/consume.py
ocean_provider/routes/encrypt.py

Set logging level to debug for all messages which logging the asset urls. 
Debug mode should be enabled only during development and usually not for production environment, which further prevent the asset url exposure to risk

Log messages with asset url only if debug is enabled

---

.bumpversion.cfg
ocean_provider/routes/consume.py
setup.py
tests/test_download.py

Signed-off-by: Pablo Maldonado <pablo@oceanprotocol.com>
Fixes #418  .
- Retrieve c2d environments and compare consumer address with the service id to allow or block download

Fix c2d address detection in download endpoint

---

.bumpversion.cfg
.github/workflows/pytest.yml
ocean_provider/utils/accounts.py
ocean_provider/utils/util.py
setup.py
tests/test_compute.py

refactor signatures

---

ocean_provider/run.py

Closes #423. It doesn't seem it was crashing, just logging the error. However, I think we shouldn't log 404 as errors. We already have the "incoming request" logger and I believe that to be enough.
Alternately I can log it as info, if needed.

Removes error logging for 404 code.

---

.github/workflows/pytest.yml
README.md
ocean_provider/routes/consume.py
ocean_provider/utils/accounts.py
ocean_provider/utils/proof.py
ocean_provider/utils/util.py
ocean_provider/validation/algo.py
setup.py
tests/test_helpers.py
tests/test_proof.py

Adds proofs, pending downloaded bytes

---

ocean_provider/utils/datatoken.py
ocean_provider/validation/test/test_algo_validation.py
tests/helpers/ddo_dict_builders.py
tests/test_download.py
tests/test_helpers.py

Fixes #442.
- Enforce order timeout when consuming an asset (download or c2d).  If timeout == 0, order valid forever. else, reject request if current timestamp - order timestamp > timeout.
- Add `test_download_timeout` integration test 
- Formatting changes using black, isort, and flake8

Issue442 enforce order timeout

---

ocean_provider/routes/consume.py
ocean_provider/serializers.py
ocean_provider/utils/asset.py
ocean_provider/utils/basics.py
ocean_provider/utils/datatoken.py
ocean_provider/utils/error_responses.py
ocean_provider/utils/util.py
ocean_provider/validation/algo.py
tests/test_download.py
tests/test_helpers.py

Towards #442.
- Enforce order timeout when consuming an asset (download or c2d). If timeout == 0, order valid forever. else, reject request if current timestamp - order timestamp > timeout.
- Add `test_download_timeout`
- Ensure that errors in `validate_order_tx` result in 400 error responses (previously resulted in 503)
- Move `get_metadata_url` and `get_datatoken_minter` to fix circular import issues
- Add `service_timeout` argument to `verify_order_tx`
- Add `timeout` argument to the `get_dataset_ddo_with_access_service` test helper method
- Remove `verify_order_tx` from the `send_order` test helper method, unnecessary.

Issue442 enforce order timeout v3

---

ocean_provider/routes/consume.py
ocean_provider/utils/datatoken.py
tests/helpers/compute_helpers.py
tests/helpers/ddo_dict_builders.py
tests/test_helpers.py
tests/test_initialize.py

Towards #442
- Test initialize compute, reuse order but the order is expired
- Improve debug log inside `verify_order_tx`
- Add `timeout` argument to `get_compute_service`, `get_compute_service_no_rawalgo`, and `build_custom_services`

Add initialize compute timeout tests

---

.bumpversion.cfg
.github/workflows/pytest.yml
ocean_provider/config.py
ocean_provider/routes/compute.py
ocean_provider/utils/basics.py
ocean_provider/utils/provider_fees.py
setup.py
tests/helpers/compute_helpers.py
tests/test_compute.py
tests/test_initialize.py

When a initializeCompute endpoint is called, we should always check if existing orders are valid until validUntil, and not the current timestamp
Main fix is one line in [ocean_provider/utils/provider_fees.py](https://github.com/oceanprotocol/provider/pull/487/files#diff-63b62246fbc8da10a0f1dfe53c633bada9fc1a20a65628433e7bcaa69d61fd57)
Rest is just test adjustments

fix validUntil usage

---

.bumpversion.cfg
ocean_provider/routes/consume.py
ocean_provider/utils/datatoken.py
ocean_provider/utils/provider_fees.py
ocean_provider/validation/algo.py
ocean_provider/validation/test/test_algo_validation.py
setup.py

- make sure we always return correct startOrder tx_id, even if caller sends a reuseOrder tx
- add extra debug logging

Fix InitializeCompute flow

---

ocean_provider/validation/RBAC.py
tests/test_RBAC.py
tests/test_compute.py

Fixes #446  .
- updated RBAC encrypt request.

Modified encrypt payload for RBAC.

---

ocean_provider/routes/compute.py
ocean_provider/utils/error_responses.py
ocean_provider/validation/algo.py
ocean_provider/validation/images.py
ocean_provider/validation/test/test_algo_validation.py
tests/test_compute.py
tests/test_routes.py

Validation errors

---

.github/workflows/pytest.yml
ocean_provider/file_types/file_types.py
ocean_provider/file_types/file_types_factory.py
ocean_provider/utils/test/test_util.py
tests/helpers/ddo_dict_builders.py
tests/test_graphql.py
tests/test_helpers.py

Closes #538 
- add 'graphql' storage type
How to use it:
- before running barge, do ' export PROVIDER_VERSION=graphql'
- when publishing your asset, using ocean.js/py , use something like:
```
[
{
"type": "graphql",
"url": "http://172.15.0.15:8000/subgraphs/name/oceanprotocol/ocean-subgraph",
"query": """
query{
nfts(orderBy: createdTimestamp,orderDirection:desc){
id
symbol
createdTimestamp
}
}
""",
}
]
```
instead of regular URL like:
```
[
{
"url": "https://raw.githubusercontent.com/tbertinmahieux/MSongsDB/master/Tasks_Demos/CoverSongs/shs_dataset_test.txt",
"type": "url",
"method": "GET",
}
]
```

add basic graphql support

---

README.md
ocean_provider/config.py
ocean_provider/utils/basics.py
ocean_provider/utils/test/test_basics.py

Closes #556.
Tested with the same URL locally and reproduced easily. I concluded that using an env var is unreliable, so I changed the check to detect the specific ExtraDataLength error, just like in Aquarius where it properly works.

Fixes POA detection, remove env setting for POA.

---

ocean_provider/utils/datatoken.py

Fixes #569 .
- convert datatoken address to checksum before query with web3.py

convert datatoken address to checksum before check isDeployed

---

API.md

Document initialize Compute.

---

ocean_provider/routes/README.md
ocean_provider/routes/auth.py
tests/test_auth.py

Document errors (follow-up)

---

ocean_provider/utils/datatoken.py
ocean_provider/utils/provider_fees.py
tests/test_download.py
tests/test_helpers.py

Fix Incorrect event validation

---

ocean_provider/utils/accounts.py
ocean_provider/validation/provider_requests.py

Output error message from Invalid Signature request.

---

ocean_provider/http_provider.py
ocean_provider/utils/basics.py

As seen in https://github.com/oceanprotocol/aquarius/pull/1010. It might not have the same issues as Aquarius, since Aquarius has an upgraded web3.py which causes the issues. However, to be on the safe side, I added these changes here as well.

Correct header usage.

---

ocean_provider/routes/compute.py
ocean_provider/utils/accounts.py
ocean_provider/utils/compute.py
ocean_provider/utils/test/test_accounts.py
pytest.ini

Fixes #653  .
- refactor logic in `sign_for_compute`
- determine nonce format with conditional cast (either int, either float)

Refactor compute signature logic.

---

.github/workflows/pytest.yml
ocean_provider/run.py
ocean_provider/utils/accounts.py
ocean_provider/utils/data_nft.py
ocean_provider/utils/test/test_accounts.py
ocean_provider/utils/test/test_compute.py
ocean_provider/utils/test/test_provider_fees.py
ocean_provider/validation/test/test_algo_validation.py
tests/helpers/compute_helpers.py
tests/helpers/nonce.py
tests/test_compute.py
tests/test_helpers.py
tests/test_initialize.py
tests/test_routes.py

- 
Good news is that almost all test are passing locally
```
(provider) alx@ubuntu:/ocean/provider$ coverage run --source ocean_provider -m pytest
============================= test session starts ==============================
platform linux -- Python 3.8.10, pytest-7.1.2, pluggy-1.0.0
rootdir: /ocean/provider, configfile: pytest.ini
plugins: env-0.6.2, web3-5.25.0
collected 136 items                                                            
ocean_provider/test/test_user_nonce.py ...                               [  2%]
ocean_provider/utils/test/test_accounts.py ...                           [  4%]
ocean_provider/utils/test/test_address.py ...                            [  6%]
ocean_provider/utils/test/test_basics.py ........                        [ 12%] …
```

re-enable c2d tests

---

.github/workflows/pytest.yml
Dockerfile

Fixes #654  .
- optimize Dockerfile

Optimize Dockerfile.

---

ocean_provider/file_types/definitions.py
ocean_provider/file_types/file_types.py
ocean_provider/utils/test/test_util.py
tests/test_fileinfo.py

Fixes # .
- Added check for file path validation inside UrlFile class.
- Fix fileinfo for arweave file.
- Updated tests.

Fix fileinfo for arweave file
